name: REUSE Compliance Check

on:
  push:

jobs:
  test:
    name: Check compliance
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: REUSE Compliance Check
      uses: fsfe/reuse-action@v1
      with:
        args: lint
